datasets:
  medpix_single:
    data_type: images

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage:
            - # path/dataset/MedPix/data_csv/MedPix_single_train.csv
      images:
          storage: # path/dataset/MedPix/MedPix/images
